# Generated by Django 3.1.1 on 2020-09-14 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20200914_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeemachine',
            name='model_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='machines.category'),
        ),
    ]
