# Generated by Django 3.1.1 on 2020-09-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_auto_20200914_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeemachine',
            old_name='PACKAGE_SIZE',
            new_name='Package_size',
        ),
    ]
