# Generated by Django 3.1.1 on 2020-09-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_auto_20200914_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeePods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pods_title', models.CharField(max_length=50)),
                ('pods_type', models.CharField(blank=True, choices=[('Coffee Pod Large', 'Coffee Pod Large'), ('Coffee Pod Small', 'Coffee Pod Small'), ('Espresso Pod', 'Espresso Pod')], max_length=50)),
                ('coffee_flavor', models.CharField(blank=True, choices=[('Coffee Flavor Vanilla', 'Coffee Flavor Vanilla'), ('Coffee Flavor Caramel', 'Coffee Flavor Caramel'), ('Coffee Flavor Psl', 'Coffee Flavor Psl'), ('Coffee Flavor Mocha', 'Coffee Flavor Mocha'), ('Coffee Flavor Hazelunt', 'Coffee Flavor Hazelunt')], max_length=50)),
                ('Package_size', models.CharField(blank=True, choices=[('1 dozen (12)', '1 dozen (12)'), ('3 dozen (36)', '3 dozen (36)'), ('5 dozen (60)', '5 dozen (60)'), ('7 dozen (84)', '7 dozen (84)')], max_length=50)),
                ('Category', models.CharField(blank=True, choices=[('Base', 'Base'), ('Premium', 'Premium'), ('Deluxe', 'Deluxe')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='coffeemachine',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='coffeemachine',
            name='Package_size',
        ),
        migrations.RemoveField(
            model_name='coffeemachine',
            name='coffee_flavor',
        ),
        migrations.RemoveField(
            model_name='coffeemachine',
            name='pods_type',
        ),
    ]
