# Generated by Django 3.1.1 on 2020-09-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_auto_20200914_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoffeePods',
        ),
    ]
